# Generated by Django 3.2.13 on 2022-09-30 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('speech_detected', models.IntegerField(default=0)),
                ('speech_analyzed', models.SmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
                ('filename', models.CharField(default='', max_length=200)),
                ('folder_name', models.CharField(default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings_2', to='exams.exam')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings_1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
